# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_stream.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'audio_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61udio_stream.proto\x12\x14real_time_processing\"\xa7\x01\n\x0c\x41udioSegment\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x37\n\x0c\x61udio_format\x18\x03 \x01(\x0e\x32!.real_time_processing.AudioFormat\x12\x17\n\x0fsequence_number\x18\x04 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x10\n\x08is_final\x18\x06 \x01(\x08\"U\n\x0eIngestResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\r\x12\x16\n\x0estatus_message\x18\x03 \x01(\t\"~\n\x15TranscriptionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\r\x12\x12\n\ntranscript\x18\x03 \x01(\t\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\x12\n\nconfidence\x18\x05 \x01(\x02*I\n\x0b\x41udioFormat\x12\x1c\n\x18\x41UDIO_FORMAT_UNSPECIFIED\x10\x00\x12\x08\n\x04PCMU\x10\x01\x12\x08\n\x04PCMA\x10\x02\x12\x08\n\x04OPUS\x10\x03\x32n\n\x0cStreamIngest\x12^\n\x12IngestAudioSegment\x12\".real_time_processing.AudioSegment\x1a$.real_time_processing.IngestResponse2y\n\x0cSpeechToText\x12i\n\x16TranscribeAudioSegment\x12\".real_time_processing.AudioSegment\x1a+.real_time_processing.TranscriptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFORMAT']._serialized_start=429
  _globals['_AUDIOFORMAT']._serialized_end=502
  _globals['_AUDIOSEGMENT']._serialized_start=45
  _globals['_AUDIOSEGMENT']._serialized_end=212
  _globals['_INGESTRESPONSE']._serialized_start=214
  _globals['_INGESTRESPONSE']._serialized_end=299
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=301
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=427
  _globals['_STREAMINGEST']._serialized_start=504
  _globals['_STREAMINGEST']._serialized_end=614
  _globals['_SPEECHTOTEXT']._serialized_start=616
  _globals['_SPEECHTOTEXT']._serialized_end=737
# @@protoc_insertion_point(module_scope)
