# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import audio_stream_pb2 as audio__stream__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audio_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamIngestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestAudioSegment = channel.unary_unary(
                '/real_time_processing.StreamIngest/IngestAudioSegment',
                request_serializer=audio__stream__pb2.AudioSegment.SerializeToString,
                response_deserializer=audio__stream__pb2.IngestResponse.FromString,
                _registered_method=True)


class StreamIngestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestAudioSegment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestAudioSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestAudioSegment,
                    request_deserializer=audio__stream__pb2.AudioSegment.FromString,
                    response_serializer=audio__stream__pb2.IngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'real_time_processing.StreamIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('real_time_processing.StreamIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamIngest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestAudioSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/real_time_processing.StreamIngest/IngestAudioSegment',
            audio__stream__pb2.AudioSegment.SerializeToString,
            audio__stream__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpeechToTextStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeAudioSegment = channel.unary_unary(
                '/real_time_processing.SpeechToText/TranscribeAudioSegment',
                request_serializer=audio__stream__pb2.AudioSegment.SerializeToString,
                response_deserializer=audio__stream__pb2.TranscriptionResponse.FromString,
                _registered_method=True)


class SpeechToTextServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeAudioSegment(self, request, context):
        """Sends a segment for transcription, could be part of a stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechToTextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeAudioSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeAudioSegment,
                    request_deserializer=audio__stream__pb2.AudioSegment.FromString,
                    response_serializer=audio__stream__pb2.TranscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'real_time_processing.SpeechToText', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('real_time_processing.SpeechToText', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechToText(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeAudioSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/real_time_processing.SpeechToText/TranscribeAudioSegment',
            audio__stream__pb2.AudioSegment.SerializeToString,
            audio__stream__pb2.TranscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
