// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audio_stream.proto

package real_time_processing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AudioFormat int32

const (
	AudioFormat_AUDIO_FORMAT_UNSPECIFIED AudioFormat = 0
	AudioFormat_PCMU                     AudioFormat = 1
	AudioFormat_PCMA                     AudioFormat = 2
	AudioFormat_OPUS                     AudioFormat = 3
)

var AudioFormat_name = map[int32]string{
	0: "AUDIO_FORMAT_UNSPECIFIED",
	1: "PCMU",
	2: "PCMA",
	3: "OPUS",
}

var AudioFormat_value = map[string]int32{
	"AUDIO_FORMAT_UNSPECIFIED": 0,
	"PCMU":                     1,
	"PCMA":                     2,
	"OPUS":                     3,
}

func (x AudioFormat) String() string {
	return proto.EnumName(AudioFormat_name, int32(x))
}

func (AudioFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a44c7c16779365d, []int{0}
}

type AudioSegment struct {
	SessionId            string      `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp            int64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AudioFormat          AudioFormat `protobuf:"varint,3,opt,name=audio_format,json=audioFormat,proto3,enum=real_time_processing.AudioFormat" json:"audio_format,omitempty"`
	SequenceNumber       uint32      `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Data                 []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	IsFinal              bool        `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AudioSegment) Reset()         { *m = AudioSegment{} }
func (m *AudioSegment) String() string { return proto.CompactTextString(m) }
func (*AudioSegment) ProtoMessage()    {}
func (*AudioSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a44c7c16779365d, []int{0}
}

func (m *AudioSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioSegment.Unmarshal(m, b)
}
func (m *AudioSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioSegment.Marshal(b, m, deterministic)
}
func (m *AudioSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioSegment.Merge(m, src)
}
func (m *AudioSegment) XXX_Size() int {
	return xxx_messageInfo_AudioSegment.Size(m)
}
func (m *AudioSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioSegment.DiscardUnknown(m)
}

var xxx_messageInfo_AudioSegment proto.InternalMessageInfo

func (m *AudioSegment) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AudioSegment) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AudioSegment) GetAudioFormat() AudioFormat {
	if m != nil {
		return m.AudioFormat
	}
	return AudioFormat_AUDIO_FORMAT_UNSPECIFIED
}

func (m *AudioSegment) GetSequenceNumber() uint32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *AudioSegment) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AudioSegment) GetIsFinal() bool {
	if m != nil {
		return m.IsFinal
	}
	return false
}

type IngestResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber       uint32   `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	StatusMessage        string   `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IngestResponse) Reset()         { *m = IngestResponse{} }
func (m *IngestResponse) String() string { return proto.CompactTextString(m) }
func (*IngestResponse) ProtoMessage()    {}
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a44c7c16779365d, []int{1}
}

func (m *IngestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngestResponse.Unmarshal(m, b)
}
func (m *IngestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngestResponse.Marshal(b, m, deterministic)
}
func (m *IngestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngestResponse.Merge(m, src)
}
func (m *IngestResponse) XXX_Size() int {
	return xxx_messageInfo_IngestResponse.Size(m)
}
func (m *IngestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IngestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IngestResponse proto.InternalMessageInfo

func (m *IngestResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *IngestResponse) GetSequenceNumber() uint32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *IngestResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type TranscriptionResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber       uint32   `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Transcript           string   `protobuf:"bytes,3,opt,name=transcript,proto3" json:"transcript,omitempty"`
	IsFinal              bool     `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Confidence           float32  `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscriptionResponse) Reset()         { *m = TranscriptionResponse{} }
func (m *TranscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*TranscriptionResponse) ProtoMessage()    {}
func (*TranscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a44c7c16779365d, []int{2}
}

func (m *TranscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscriptionResponse.Unmarshal(m, b)
}
func (m *TranscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscriptionResponse.Marshal(b, m, deterministic)
}
func (m *TranscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscriptionResponse.Merge(m, src)
}
func (m *TranscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_TranscriptionResponse.Size(m)
}
func (m *TranscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranscriptionResponse proto.InternalMessageInfo

func (m *TranscriptionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *TranscriptionResponse) GetSequenceNumber() uint32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *TranscriptionResponse) GetTranscript() string {
	if m != nil {
		return m.Transcript
	}
	return ""
}

func (m *TranscriptionResponse) GetIsFinal() bool {
	if m != nil {
		return m.IsFinal
	}
	return false
}

func (m *TranscriptionResponse) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func init() {
	proto.RegisterEnum("real_time_processing.AudioFormat", AudioFormat_name, AudioFormat_value)
	proto.RegisterType((*AudioSegment)(nil), "real_time_processing.AudioSegment")
	proto.RegisterType((*IngestResponse)(nil), "real_time_processing.IngestResponse")
	proto.RegisterType((*TranscriptionResponse)(nil), "real_time_processing.TranscriptionResponse")
}

func init() {
	proto.RegisterFile("audio_stream.proto", fileDescriptor_5a44c7c16779365d)
}

var fileDescriptor_5a44c7c16779365d = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x51, 0x8f, 0x12, 0x31,
	0x10, 0xb6, 0x1c, 0x9e, 0x30, 0xc7, 0x21, 0x69, 0xd4, 0xac, 0xe6, 0x34, 0x2b, 0xd1, 0xb8, 0xd1,
	0x04, 0x12, 0xfc, 0x05, 0x78, 0x1c, 0xc9, 0x3e, 0x70, 0x90, 0x02, 0x2f, 0x3e, 0xd8, 0x94, 0x65,
	0xc0, 0x26, 0x6c, 0xbb, 0xb6, 0xe5, 0x94, 0x27, 0xff, 0x97, 0xff, 0xc8, 0x7f, 0x61, 0xb6, 0xcb,
	0x79, 0x90, 0x6c, 0x34, 0x26, 0x3e, 0xed, 0xf4, 0xeb, 0xb7, 0xf3, 0xcd, 0xcc, 0x37, 0x05, 0x2a,
	0xb6, 0x4b, 0xa9, 0xb9, 0x75, 0x06, 0x45, 0xda, 0xc9, 0x8c, 0x76, 0x9a, 0x3e, 0x32, 0x28, 0x36,
	0xdc, 0xc9, 0x14, 0x79, 0x66, 0x74, 0x82, 0xd6, 0x4a, 0xb5, 0x6e, 0xff, 0x24, 0xd0, 0xe8, 0xe7,
	0xe4, 0x29, 0xae, 0x53, 0x54, 0x8e, 0x3e, 0x07, 0xb0, 0xf9, 0x9d, 0x56, 0x5c, 0x2e, 0x03, 0x12,
	0x92, 0xa8, 0xce, 0xea, 0x7b, 0x24, 0x5e, 0xd2, 0x0b, 0xa8, 0xe7, 0x29, 0xac, 0x13, 0x69, 0x16,
	0x54, 0x42, 0x12, 0x9d, 0xb0, 0x3b, 0x80, 0x0e, 0xa0, 0x51, 0x28, 0xaf, 0xb4, 0x49, 0x85, 0x0b,
	0x4e, 0x42, 0x12, 0x35, 0x7b, 0x2f, 0x3b, 0x65, 0xd2, 0x1d, 0x2f, 0x3b, 0xf4, 0x44, 0x76, 0x26,
	0xee, 0x0e, 0xf4, 0x0d, 0x3c, 0xb4, 0xf8, 0x65, 0x8b, 0x2a, 0x41, 0xae, 0xb6, 0xe9, 0x02, 0x4d,
	0x50, 0x0d, 0x49, 0x74, 0xce, 0x9a, 0xb7, 0xf0, 0xb5, 0x47, 0x29, 0x85, 0xea, 0x52, 0x38, 0x11,
	0xdc, 0x0f, 0x49, 0xd4, 0x60, 0x3e, 0xa6, 0x4f, 0xa1, 0x26, 0x2d, 0x5f, 0x49, 0x25, 0x36, 0xc1,
	0x69, 0x48, 0xa2, 0x1a, 0x7b, 0x20, 0xed, 0x30, 0x3f, 0xb6, 0xbf, 0x43, 0x33, 0x56, 0x6b, 0xb4,
	0x8e, 0xa1, 0xcd, 0xb4, 0xb2, 0xf8, 0xb7, 0x66, 0x4b, 0x0a, 0xa9, 0x94, 0x16, 0xf2, 0x1a, 0x9a,
	0xd6, 0x09, 0xb7, 0xb5, 0x3c, 0x45, 0x6b, 0xc5, 0x1a, 0x7d, 0xe7, 0x75, 0x76, 0x5e, 0xa0, 0xa3,
	0x02, 0x6c, 0xff, 0x20, 0xf0, 0x78, 0x66, 0x84, 0xb2, 0x89, 0x91, 0x99, 0x93, 0x5a, 0xfd, 0xf7,
	0x42, 0x5e, 0x00, 0xb8, 0xdf, 0x02, 0xfb, 0x22, 0x0e, 0x90, 0xa3, 0xe9, 0x54, 0x8f, 0xa6, 0x93,
	0xff, 0x9a, 0x68, 0xb5, 0x92, 0xcb, 0x3c, 0x9d, 0x1f, 0x69, 0x85, 0x1d, 0x20, 0x6f, 0x63, 0x38,
	0x3b, 0x70, 0x8c, 0x5e, 0x40, 0xd0, 0x9f, 0x0f, 0xe2, 0x31, 0x1f, 0x8e, 0xd9, 0xa8, 0x3f, 0xe3,
	0xf3, 0xeb, 0xe9, 0xe4, 0xea, 0x32, 0x1e, 0xc6, 0x57, 0x83, 0xd6, 0x3d, 0x5a, 0x83, 0xea, 0xe4,
	0x72, 0x34, 0x6f, 0x91, 0x7d, 0xd4, 0x6f, 0x55, 0xf2, 0x68, 0x3c, 0x99, 0x4f, 0x5b, 0x27, 0x3d,
	0x05, 0x8d, 0xa9, 0x5f, 0xcd, 0xc2, 0x0e, 0xfa, 0x09, 0x68, 0x11, 0x1d, 0x6d, 0x62, 0xfb, 0x0f,
	0x6b, 0xb3, 0xe7, 0x3c, 0x7b, 0x55, 0xce, 0x39, 0xb6, 0xb9, 0xb7, 0x83, 0xc6, 0x34, 0x43, 0x4c,
	0x3e, 0xcf, 0xf4, 0x0c, 0xbf, 0x39, 0x2a, 0xe1, 0xc9, 0xad, 0x0d, 0x0b, 0xfc, 0x67, 0xcd, 0x77,
	0xe5, 0x9c, 0x52, 0x63, 0x3f, 0x0c, 0x3f, 0x0e, 0x0c, 0xde, 0xe8, 0x1b, 0x2d, 0x13, 0x14, 0xb2,
	0xeb, 0xbf, 0x7c, 0x2d, 0x1c, 0x7e, 0x15, 0x3b, 0xbe, 0x11, 0x3b, 0x34, 0x5d, 0xa9, 0x1c, 0x1a,
	0x25, 0x36, 0x5d, 0xff, 0x4e, 0x6d, 0xb7, 0x2c, 0xfb, 0xe2, 0xd4, 0x5f, 0xbe, 0xff, 0x15, 0x00,
	0x00, 0xff, 0xff, 0xa9, 0xc4, 0x1e, 0x53, 0xda, 0x03, 0x00, 0x00,
}
