# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dialogue_management_service_pb2 as dialogue__management__service__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dialogue_management_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DialogueManagementServiceStub(object):
    """DialogueManagementService definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ManageTurn = channel.unary_unary(
                '/ai_ml_services.dialogue_management.DialogueManagementService/ManageTurn',
                request_serializer=dialogue__management__service__pb2.DialogueRequest.SerializeToString,
                response_deserializer=dialogue__management__service__pb2.DialogueResponse.FromString,
                _registered_method=True)


class DialogueManagementServiceServicer(object):
    """DialogueManagementService definition
    """

    def ManageTurn(self, request, context):
        """Manages a turn in the conversation based on NLU input
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DialogueManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ManageTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageTurn,
                    request_deserializer=dialogue__management__service__pb2.DialogueRequest.FromString,
                    response_serializer=dialogue__management__service__pb2.DialogueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_ml_services.dialogue_management.DialogueManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_ml_services.dialogue_management.DialogueManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DialogueManagementService(object):
    """DialogueManagementService definition
    """

    @staticmethod
    def ManageTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_ml_services.dialogue_management.DialogueManagementService/ManageTurn',
            dialogue__management__service__pb2.DialogueRequest.SerializeToString,
            dialogue__management__service__pb2.DialogueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
